let REACT_APP_API_URL = process.env.REACT_APP_API_URL;
let REACT_APP_API_URL_ENC_KEY = process.env.REACT_APP_API_URL_ENC_KEY;
let REACT_APP_API_URL_DEC_KEY = process.env.REACT_APP_API_URL_DEC_KEY;

export {
  REACT_APP_API_URL,
  REACT_APP_API_URL_ENC_KEY,
  REACT_APP_API_URL_DEC_KEY,
};
