let REACT_APP_API_URL = process.env.REACT_APP_API_URL;
let REACT_APP_API_URL_TOUR_INFO = process.env.REACT_APP_API_URL_TOUR_INFO;
let REACT_APP_API_URL_PEAK_INFO = process.env.REACT_APP_API_URL_PEAK_INFO;
let REACT_APP_API_URL_CULTURE_INFO = process.env.REACT_APP_API_URL_CULTURE_INFO;
let REACT_APP_API_URL_TRAFFIC_INFO = process.env.REACT_APP_API_URL_TRAFFIC_INFO;
let REACT_APP_API_URL_WILD_INFO = process.env.REACT_APP_API_URL_WILD_INFO;
let REACT_APP_API_URL_ENC_KEY = process.env.REACT_APP_API_URL_ENC_KEY;
let REACT_APP_API_URL_DEC_KEY = process.env.REACT_APP_API_URL_DEC_KEY;

export {
  REACT_APP_API_URL,
  REACT_APP_API_URL_TOUR_INFO,
  REACT_APP_API_URL_PEAK_INFO,
  REACT_APP_API_URL_CULTURE_INFO,
  REACT_APP_API_URL_TRAFFIC_INFO,
  REACT_APP_API_URL_WILD_INFO,
  REACT_APP_API_URL_ENC_KEY,
  REACT_APP_API_URL_DEC_KEY,
};
